theme = "vitesse_dark"

[editor]
mouse = false
default-yank-register = "+"
shell = ["powershell.exe", "-c"]
bufferline = "always"
color-modes = true
undercurl = true
popup-border = "all"

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.auto-save]
after-delay.enable = true
after-delay.timeout = 1000

[editor.lsp]
display-messages = true

[editor.statusline]
left = ["mode", "workspace-diagnostics", "spinner", "spacer", "version-control"]
right = ["position", "selections", "file-type"]
